src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?int $argent = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Groupe $groupe = null;

    public function __construct()
    {
        $this->roles = ['ROLE_USER'];
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function addRole(string $role): self
    {
        if (!in_array($role, $this->roles, true)) {
            $this->roles[] = $role;
        }

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getArgent(): ?int
    {
        return $this->argent;
    }

    public function setArgent(int $argent): static
    {
        $this->argent = $argent;

        return $this;
    }

    public function getGroupe(): ?Groupe
    {
        return $this->groupe;
    }

    public function setGroupe(?Groupe $groupe): static
    {
        $this->groupe = $groupe;

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    #[Route(path: '/', name: 'app_login')]
    public function login(AuthenticationUtils $authenticationUtils): Response
    {
        // if ($this->getUser()) {
        //     return $this->redirectToRoute('target_path');
        // }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error]);
    }

    #[Route(path: '/logout', name: 'app_logout')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }
}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block title %}Log in!
{% endblock %}

{% block body %}
	<div class="flex h-screen bg-gray-100">

		<div class="flex flex-col flex-1">

			<div class="container mx-auto px-4 py-8">
				<div class="max-w-md mx-auto bg-white rounded p-6 shadow-md">
					<h2 class="text-2xl font-bold mb-6">Connectez-vous à votre compte</h2>
					<form method="post">
						{% if error %}
							<div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
						{% endif %}

						{% if app.user %}
							<div class="mb-3">
								You are logged in as
								{{ app.user.userIdentifier }},
								<a href="{{ path('app_logout') }}">Logout</a>
							</div>
						{% endif %}
						<div class="mb-4">
							<label for="inputEmail" class="block text-gray-700 text-sm font-bold mb-2">Adresse e-mail</label>
							<input type="email" id="inputEmail" name="email" value="{{ last_username }}" class="w-full border border-gray-300 rounded py-2 px-3 focus:outline-none focus:border-indigo-500 form-control" placeholder="Adresse e-mail" autocomplete="email" required autofocus>
						</div>
						<div class="mb-4">
							<label for="inputPassword" class="block text-gray-700 text-sm font-bold mb-2">Mot de passe</label>
							<input type="password" name="password" id="inputPassword" class="w-full border border-gray-300 rounded py-2 px-3 focus:outline-none focus:border-indigo-500 form-control" autocomplete="current-password" placeholder="Mot de passe" required>
							<input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
						</div>
						<button type="submit" class="bg-indigo-500 hover:bg-indigo-600 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Se connecter</button>
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock %}